runtime: nodejs20

handlers:
  # Serve all static files from the dist folder
  - url: /
    static_dir: dist

  # Serve the index.html file for all other requests
  - url: /.*
    static_files: dist/index.html
    upload: dist/index.html
    http_headers:
      Content-Type: text/html; charset=utf-8

automatic_scaling:
  target_cpu_utilization: 0.65
  target_throughput_utilization: 0.75
  min_instances: 1
