name: Source Code Linting

on: [push, pull_request]

jobs:
  frontend-lint-check:
    name: Frontend lint check
    runs-on: ubuntu-latest
    # This runs if the event is not a pull request or if the pull request is from a fork
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install frontend dependencies
        run: npm ci
        working-directory: ./frontend

      - name: Lint frontend
        run: npm run lint
        working-directory: ./frontend

  backend-lint-check:
    name: Backend lint check
    runs-on: ubuntu-latest
    # This runs if the event is not a pull request or if the pull request is from a fork
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install backend dependencies
        run: npm ci
        working-directory: "./backend"

      - name: Lint backend
        run: npm run lint
        working-directory: "./backend"
